### ISSUE TITLE
Revoke command doesn't work

### ISSUE THREAD

**Issue by realmfoo** [alxmsl/GoogleClient#8]
It creates URL as `https://www.googleapis.com/androidpublisher/v2/applications/packageName/purchases/subscriptions/subscriptionId/tokens/token/:revoke` with redundant slash before `:revoke`.

https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/revoke?hl=ru

**Comment by alxmsl** [comment]
It's already fixed since [v2.0.2](https://github.com/alxmsl/GoogleClient/releases/tag/v2.0.2)
